services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: bifrost-api
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://bifrost:bifrost@db:5432/bifrost
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api/app:/app/app
    depends_on:
      - db
      - redis

  redis:
    image: redis:7-alpine
    container_name: bifrost-redis
    command: redis-server --save "" --appendonly no
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    container_name: bifrost-db
    environment:
      POSTGRES_USER: bifrost
      POSTGRES_PASSWORD: bifrost
      POSTGRES_DB: bifrost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-bifrost} -d ${POSTGRES_DB:-bifrost}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
